export const GET_ARTICLES_START = "GET_ARTICLES_START";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAIL = "GET_ARTICLES_FAIL";

export const GET_ARTICLES_SEARCH = "GET_ARTICLES_SEARCH";
export const GET_ARTICLES_INIT = "GET_ARTICLES_INIT";
