export const GET_ARTICLES_START = "GET_ARTICLES_START";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAIL = "GET_ARTICLES_FAIL";

export const GET_NEXT_PAGE_ARTICLES = "GET_NEXT_PAGE_ARTICLES";
export const GET_NEXT_PAGE_ARTICLES_START = "GET_NEXT_PAGE_ARTICLES_START";
export const GET_NEXT_PAGE_ARTICLES_SUCCESS = "GET_NEXT_PAGE_ARTICLES_SUCCESS";
export const GET_NEXT_PAGE_ARTICLES_FAIL = "GET_NEXT_PAGE_ARTICLES_FAIL";

export const CLEAR_ARTICLES = "CLEAR_ARTICLES";
export const CLEAR_ARTICLES_START = "CLEAR_ARTICLES_START";
export const CLEAR_ARTICLES_SUCCESS = "CLEAR_ARTICLES_SUCCESS";

export const GET_ARTICLES_SEARCH = "GET_ARTICLES_SEARCH";
export const GET_ARTICLES_INIT = "GET_ARTICLES_INIT";
